# Copyright 2026 Michael Timothy Bennett
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""ttgs_simulation.py

Reproducibility script for the TTGS spacetime bound manuscript.

This script regenerates every figure and every LaTeX table or macro file that the manuscript inputs.

Scientific target
The manuscript studies the inequality

    D <= kappa * v * theta

D is the physical diameter of the region contributing to one unified moment.
v is an upper bound on causal propagation speed through the substrate.
theta is the physical duration of the integration window.
kappa is an architecture factor. It is 1 for hub mediated exchange and 1/2 for
all to all exchange. More general graphs are treated in the manuscript.

This repository contains three kinds of results.

1. Mechanistic integration models
   These are minimal message passing models that make the bound concrete. They show a sharp fragmentation transition as D/(v*theta) crosses the predicted thresholds.

2. Measurement and inference tests
   These are Monte Carlo experiments that validate the falsification protocol and show how bad estimators can manufacture spurious violations.

3. Zero budget literature anchors
   These are reanalyses of published numbers. The primate dataset is extracted
   from Phillips et al 2015 Table 1 plus the published correction.

Outputs
The script writes the following files into the working directory.

Figures for the main manuscript
- ttgs_mechanistic_main.pdf
- ttgs_primate_main.pdf

Optional figures that are typically placed in Supplementary Information
- ttgs_mechanistic_transition.pdf
- ttgs_mechanistic_thresholds.pdf
- ttgs_literature_anchor.pdf
- ttgs_primate_scaling.pdf
- ttgs_primate_constraint.pdf
- ttgs_power_curve.pdf
- ttgs_v_estimator_tradeoff.pdf
- ttgs_dependence_thinning.pdf
- ttgs_power_vs_n.pdf

LaTeX inputs
- ttgs_mechanistic_stats.tex
- ttgs_primate_scaling_stats.tex
- ttgs_primate_constraint_stats.tex
- ttgs_v_estimator_table.tex

Data files
- ttgs_phillips2015_table1.csv

Source data directory
- ttgs_source_data/
  Each figure has a matching CSV file with the plotted values.

Run
python ttgs_simulation.py

Dependencies
numpy
scipy
matplotlib

"""

from __future__ import annotations

# Package identifier for this distribution of the code and artifacts.
PACKAGE_VERSION = "TTGS77"

# Licensing and attribution constants used in generated manifests.
LICENSE_SPDX = "Apache-2.0"
COPYRIGHT_HOLDER = "Michael Timothy Bennett"
COPYRIGHT_YEAR = 2026

import csv
import math
import os
import hashlib
import json
import sys
from datetime import datetime, timezone

# If SOURCE_DATE_EPOCH is set, use it for generated_at_utc fields so that
# manifests and provenance JSONs can be regenerated byte identically across runs.
# This mirrors common reproducible build conventions.


def source_date_epoch():
    # Return SOURCE_DATE_EPOCH if set and parseable, else None.
    val = os.environ.get('SOURCE_DATE_EPOCH')
    if val is None:
        return None
    try:
        return int(val)
    except (TypeError, ValueError):
        return None


def generated_at_utc_iso() -> str:
    sde = source_date_epoch()
    if sde is not None:
        t = datetime.fromtimestamp(sde, tz=timezone.utc)
        return t.strftime('%Y-%m-%dT%H:%M:%SZ')
    return datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

# Put matplotlib cache somewhere writable and outside the package archive.
# This avoids creating hidden build artifacts inside the submission folder.
if "MPLCONFIGDIR" not in os.environ:
    os.environ["MPLCONFIGDIR"] = "/tmp/ttgs_mplconfig"
Path(os.environ["MPLCONFIGDIR"]).mkdir(parents=True, exist_ok=True)

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import scipy


plt.switch_backend("Agg")

# Matplotlib PDF font settings
#
# Nature Portfolio production workflows reject Type 3 fonts in figure PDFs.
# Matplotlib can emit Type 3 fonts by default when saving to PDF.
# Force TrueType fonts (Type 42) so text remains editable and passes
# common journal preflight checks.
plt.rcParams["pdf.fonttype"] = 42
plt.rcParams["ps.fonttype"] = 42


# ---------------------------------------------------------------------------
# Provenance metadata for literature-derived numeric inputs
# ---------------------------------------------------------------------------
# This script is intended to be runnable offline. For that reason it contains
# literal numeric values transcribed from the cited sources.
#
# The fields below are provided so an external reader can audit where each
# literature-derived number came from.
#
# Keep any verbatim excerpts short to respect publisher policies.

LITERATURE_SOURCES = {
    "phillips2015callosal": {
        "doi": "10.1098/rspb.2015.1535",
        "pmcid": "PMC4650152",
        "venue": "Proceedings of the Royal Society B",
        "year": 2015,
        "notes": "Original article for context. Numerical Table 1 values are taken from the published correction note.",
    },
    "phillips2015corr": {
        "doi": "10.1098/rspb.2015.2620",
        "pmcid": "PMC4685830",
        "year": 2015,
        "where": "Correction note. Table 1 reproduces the corrected individual-level table.",
        "notes": "This package transcribes Table 1 and uses it as the primate anchor dataset. The correction changes Macaca nemistrina to Macaca maura.",
    },
    "innocenti2022": {
        "doi": "10.1016/j.pneurobio.2021.102186",
        "pmcid": "PMC8752969",
        "year": 2022,
        "where": "Section iii) Temporal transformations. Sentence reporting mean conduction velocities 4.9 to 11.4 m/s across species and areas.",
        "notes": "This package uses this range as a conservative callosal speed-limit anchor for the human figure.",
    },
}


def write_provenance(out_dir: Path) -> Path:
    """Write machine-readable provenance metadata for audit and reuse.

    The top-level keys match the citation handles in the LaTeX sources.
    Additional fields under _meta and _inputs provide a direct mapping from
    constants and extracted tables to their sources.
    """

    provenance = dict(LITERATURE_SOURCES)
    provenance["_meta"] = {
        "package_version": PACKAGE_VERSION,
        "license_spdx": LICENSE_SPDX,
        "copyright_holder": COPYRIGHT_HOLDER,
        "copyright_year": COPYRIGHT_YEAR,
        "license_file": "LICENSE",
        "notice_file": "NOTICE",
        "generated_at_utc": generated_at_utc_iso(),
        "source_date_epoch": source_date_epoch(),
        "python": sys.version.split()[0],
        "numpy": np.__version__,
        "scipy": scipy.__version__,
        "matplotlib": plt.matplotlib.__version__,
    }

    provenance["_inputs"] = [
        {
            "name": "PHILLIPS_TABLE1_CSV",
            "file": "ttgs_phillips2015_table1.csv",
            "source": "phillips2015corr",
            "notes": "Direct transcription of Table 1 in the published correction note.",
        },
        {
            "name": "CALLOSAL_V_LO_M_PER_S",
            "value": CALLOSAL_V_LO_M_PER_S,
            "units": "m/s",
            "source": "innocenti2022",
            "notes": "Lower end of the reported mean conduction velocity range.",
        },
        {
            "name": "CALLOSAL_V_HI_M_PER_S",
            "value": CALLOSAL_V_HI_M_PER_S,
            "units": "m/s",
            "source": "innocenti2022",
            "notes": "Upper end of the reported mean conduction velocity range.",
        },
        {
            "name": "DENSITY_G_PER_CM3",
            "value": DENSITY_G_PER_CM3,
            "units": "g/cm^3",
            "source": "assumption",
            "notes": "Assumed brain tissue density for sphere-equivalent diameter conversion.",
        },
        {
            "name": "DIAMETER_PADDING_FRAC",
            "value": DIAMETER_PADDING_FRAC,
            "units": "dimensionless",
            "source": "assumption",
            "notes": "Padding applied to sphere-equivalent diameters to avoid accidental underestimation.",
        },
    ]

    path = out_dir / "ttgs_provenance.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(provenance, f, indent=2, sort_keys=True)
    return path


# ----------------------------
# Global reproducibility knobs
# ----------------------------

SEED = 12345


# ----------------------------
# Literature anchored constants
# ----------------------------

# Conduction velocity range reported in Innocenti et al.
CALLOSAL_V_LO_M_PER_S = 4.9
CALLOSAL_V_HI_M_PER_S = 11.4

# Modelling constants for the human-scale anchor.
# Convert brain mass to an equivalent-sphere diameter by assuming a tissue
# density close to water, then pad the diameter to avoid accidental
# underestimation.
DENSITY_G_PER_CM3 = 1.0
DIAMETER_PADDING_FRAC = 0.05


# ----------------------------
# Utilities
# ----------------------------

def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            chunk = f.read(1024 * 1024)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def write_manifest(out_dir: Path) -> Path:
    source_dir = out_dir / "ttgs_source_data"
    paths: List[Path] = []
    for pattern in ["ttgs_*.pdf", "ttgs_*.tex", "ttgs_*.csv"]:
        paths.extend(sorted(out_dir.glob(pattern)))
    if source_dir.exists():
        paths.extend(sorted(source_dir.glob("*.csv")))
    script_path = out_dir / "ttgs_simulation.py"
    if script_path.exists():
        paths.append(script_path)
    provenance_path = out_dir / "ttgs_provenance.json"
    if provenance_path.exists():
        paths.append(provenance_path)
    # Deduplicate while preserving deterministic order.
    uniq: List[Path] = []
    seen: set[str] = set()
    for p in paths:
        key = str(p.relative_to(out_dir))
        if key in seen:
            continue
        seen.add(key)
        uniq.append(p)

    files: Dict[str, Dict[str, object]] = {}
    for p in uniq:
        rel = str(p.relative_to(out_dir))
        st = p.stat()
        files[rel] = {
            "bytes": int(st.st_size),
            "sha256": sha256_file(p),
        }

    manifest = {
        "package_version": PACKAGE_VERSION,
        "license_spdx": LICENSE_SPDX,
        "copyright_holder": COPYRIGHT_HOLDER,
        "copyright_year": COPYRIGHT_YEAR,
        "license_file": "LICENSE",
        "notice_file": "NOTICE",
        "generated_at_utc": generated_at_utc_iso(),
        "source_date_epoch": source_date_epoch(),
        "python": sys.version.split()[0],
        "numpy": np.__version__,
        "scipy": scipy.__version__,
        "matplotlib": plt.matplotlib.__version__,
        "files": files,
    }
    manifest_path = out_dir / "ttgs_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")
    return manifest_path


PDF_METADATA = {
    "Creator": f"ttgs_simulation.py {PACKAGE_VERSION}",
    # Remove volatile timestamps so that PDF bytes are reproducible across runs.
    "CreationDate": None,
}


def save_pdf(fig: plt.Figure, path: Path) -> None:
    fig.tight_layout()
    fig.savefig(path, format="pdf", bbox_inches="tight", metadata=PDF_METADATA)
    plt.close(fig)


def write_macros(path: Path, macros: Dict[str, str]) -> None:
    """Write a small LaTeX fragment with deterministic ordering and headers."""
    header_lines = [
        "% Copyright 2026 Michael Timothy Bennett",
        "% SPDX-License-Identifier: Apache-2.0",
        "% Generated by ttgs_simulation.py",
        "",
    ]
    lines: List[str] = []
    for name, val in macros.items():
        lines.append(rf"\newcommand{{\{name}}}{{{val}}}")
    path.write_text("\n".join(header_lines + lines) + "\n", encoding="utf-8")


def gamma2_cdf(x: np.ndarray, scale: float) -> np.ndarray:
    """CDF of Gamma(k=2, scale=scale)."""
    x = np.asarray(x)
    out = np.zeros_like(x, dtype=float)
    if scale <= 0:
        out[x >= 0] = 1.0
        out[x < 0] = 0.0
        return out
    z = x / scale
    mask = x >= 0
    out[mask] = 1.0 - np.exp(-z[mask]) * (1.0 + z[mask])
    out[~mask] = 0.0
    return out


# ----------------------------
# Mechanistic integration model
# ----------------------------

def pair_distance_fractions_on_circle(n: int) -> np.ndarray:
    """Return sin(delta/2) for all unordered pairs of n points on a circle."""
    thetas = np.linspace(0.0, 2.0 * math.pi, n, endpoint=False)
    fracs: List[float] = []
    for i in range(n):
        for j in range(i + 1, n):
            dtheta = abs(thetas[j] - thetas[i])
            dtheta = min(dtheta, 2.0 * math.pi - dtheta)
            fracs.append(math.sin(dtheta / 2.0))
    return np.array(fracs, dtype=float)


def success_prob_hub(x: float, n: int, jitter_frac: float) -> float:
    """Exact success probability for hub exchange at normalised diameter x = D/(v*theta)."""
    slack = 1.0 - x
    if slack <= 0:
        return 0.0
    if jitter_frac <= 0:
        return 1.0
    F = gamma2_cdf(np.array([slack]), scale=jitter_frac)[0]
    return float(F**n)


def success_prob_all_to_all(x: float, n: int, jitter_frac: float, fracs: np.ndarray | None = None) -> float:
    """Exact success probability for all-to-all exchange at normalised diameter x = D/(v*theta)."""
    if fracs is None:
        fracs = pair_distance_fractions_on_circle(n)
    slack = 1.0 - 2.0 * x * fracs
    if np.any(slack <= 0):
        return 0.0
    if jitter_frac <= 0:
        return 1.0
    F = gamma2_cdf(slack, scale=jitter_frac)
    logp = np.sum(np.log(F))
    return float(np.exp(logp))


def compute_transition_curves(n: int, jitter_frac: float, xs: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    fracs = pair_distance_fractions_on_circle(n)
    p_hub = np.array([success_prob_hub(float(x), n, jitter_frac) for x in xs])
    p_all = np.array([success_prob_all_to_all(float(x), n, jitter_frac, fracs) for x in xs])
    return p_hub, p_all


def bisection_x50(prob_fn, lo: float, hi: float, target: float = 0.5, iters: int = 50) -> float:
    plo = prob_fn(lo)
    phi = prob_fn(hi)
    if not (plo >= target >= phi):
        return lo if abs(plo - target) < abs(phi - target) else hi
    for _ in range(iters):
        mid = 0.5 * (lo + hi)
        pm = prob_fn(mid)
        if pm >= target:
            lo = mid
        else:
            hi = mid
    return 0.5 * (lo + hi)


def figure_mechanistic_transition(out_dir: Path, source_dir: Path) -> None:
    n = 20
    jitter_frac = 0.02
    xs = np.linspace(0.0, 1.2, 241)
    p_hub, p_all = compute_transition_curves(n=n, jitter_frac=jitter_frac, xs=xs)

    fig = plt.figure(figsize=(6.0, 3.6))
    ax = fig.add_subplot(1, 1, 1)
    ax.plot(xs, p_hub, label="Hub")
    ax.plot(xs, p_all, label="All-to-all")
    ax.axvline(1.0, linestyle="--")
    ax.axvline(0.5, linestyle="--")
    ax.set_xlabel(r"Normalised diameter $x=D/(v\theta)$")
    ax.set_ylabel("Success probability in one window")
    ax.set_ylim(-0.02, 1.02)
    ax.legend(frameon=False)
    save_pdf(fig, out_dir / "ttgs_mechanistic_transition.pdf")

    ensure_dir(source_dir)
    sd_path = source_dir / "fig_mechanistic_transition.csv"
    with sd_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["x", "p_hub", "p_all"])
        for x, ph, pa in zip(xs, p_hub, p_all):
            w.writerow([float(x), float(ph), float(pa)])


def figure_mechanistic_thresholds(out_dir: Path, source_dir: Path) -> Dict[str, str]:
    Ns = [10, 20, 40, 80]
    jitters = [0.0, 0.005, 0.01, 0.02]

    hub_x50: Dict[Tuple[int, float], float] = {}
    all_x50: Dict[Tuple[int, float], float] = {}

    for n in Ns:
        fracs = pair_distance_fractions_on_circle(n)
        for j in jitters:
            hub_fn = lambda x, n=n, j=j: success_prob_hub(x, n, j)
            all_fn = lambda x, n=n, j=j, fracs=fracs: success_prob_all_to_all(x, n, j, fracs)
            hub_x50[(n, j)] = bisection_x50(hub_fn, lo=0.0, hi=1.0)
            all_x50[(n, j)] = bisection_x50(all_fn, lo=0.0, hi=0.5)

    fig = plt.figure(figsize=(6.0, 3.6))
    ax = fig.add_subplot(1, 1, 1)
    for j in jitters:
        ax.plot(Ns, [hub_x50[(n, j)] for n in Ns], marker="o", linestyle="-", label=f"Hub j={j:.3f}")
        ax.plot(Ns, [all_x50[(n, j)] for n in Ns], marker="o", linestyle="--", label=f"All-to-all j={j:.3f}")
    ax.axhline(1.0, linestyle=":")
    ax.axhline(0.5, linestyle=":")
    ax.set_xscale("log", base=2)
    ax.set_xlabel("Number of nodes N")
    ax.set_ylabel(r"$x_{50}$ where success probability is 0.5")
    ax.set_ylim(0.0, 1.05)
    ax.legend(frameon=False, fontsize=7, ncol=2)
    save_pdf(fig, out_dir / "ttgs_mechanistic_thresholds.pdf")

    ensure_dir(source_dir)
    sd_path = source_dir / "fig_mechanistic_thresholds.csv"
    with sd_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["architecture", "N", "jitter", "x50"])
        for n in Ns:
            for j in jitters:
                w.writerow(["hub", n, j, hub_x50[(n, j)]])
                w.writerow(["all_to_all", n, j, all_x50[(n, j)]])

    hub_vals = np.array(list(hub_x50.values()))
    all_vals = np.array(list(all_x50.values()))
    macros = {
        "MechHubXmin": f"{hub_vals.min():.3f}",
        "MechHubXmax": f"{hub_vals.max():.3f}",
        "MechAllXmin": f"{all_vals.min():.3f}",
        "MechAllXmax": f"{all_vals.max():.3f}",
    }
    return macros


def figure_mechanistic_main(out_dir: Path, source_dir: Path) -> None:
    n = 20
    jitter_frac = 0.02
    xs = np.linspace(0.0, 1.2, 241)
    p_hub, p_all = compute_transition_curves(n=n, jitter_frac=jitter_frac, xs=xs)

    Ns = [10, 20, 40, 80]
    jitters = [0.0, 0.005, 0.01, 0.02]
    hub_x50 = {}
    all_x50 = {}
    for nn in Ns:
        fracs = pair_distance_fractions_on_circle(nn)
        for j in jitters:
            hub_fn = lambda x, n=nn, j=j: success_prob_hub(x, n, j)
            all_fn = lambda x, n=nn, j=j, fracs=fracs: success_prob_all_to_all(x, n, j, fracs)
            hub_x50[(nn, j)] = bisection_x50(hub_fn, lo=0.0, hi=1.0)
            all_x50[(nn, j)] = bisection_x50(all_fn, lo=0.0, hi=0.5)

    fig = plt.figure(figsize=(7.2, 3.4))
    ax1 = fig.add_subplot(1, 2, 1)
    ax1.plot(xs, p_hub, label="Hub")
    ax1.plot(xs, p_all, label="All-to-all")
    ax1.axvline(1.0, linestyle="--")
    ax1.axvline(0.5, linestyle="--")
    ax1.set_xlabel(r"$x=D/(v\theta)$")
    ax1.set_ylabel("Success probability")
    ax1.set_ylim(-0.02, 1.02)
    ax1.legend(frameon=False, fontsize=8)
    ax1.set_title("(a) Transition")

    ax2 = fig.add_subplot(1, 2, 2)
    for j in jitters:
        ax2.plot(Ns, [hub_x50[(nn, j)] for nn in Ns], marker="o", linestyle="-")
        ax2.plot(Ns, [all_x50[(nn, j)] for nn in Ns], marker="o", linestyle="--")
    ax2.axhline(1.0, linestyle=":")
    ax2.axhline(0.5, linestyle=":")
    ax2.set_xscale("log", base=2)
    ax2.set_xlabel("N")
    ax2.set_ylabel(r"$x_{50}$")
    ax2.set_ylim(0.0, 1.05)
    ax2.set_title("(b) Robustness sweep")
    save_pdf(fig, out_dir / "ttgs_mechanistic_main.pdf")

    ensure_dir(source_dir)
    sd_a = source_dir / "fig_mechanistic_main_panel_a.csv"
    with sd_a.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["x", "p_hub", "p_all"])
        for x, ph, pa in zip(xs, p_hub, p_all):
            w.writerow([float(x), float(ph), float(pa)])

    sd_b = source_dir / "fig_mechanistic_main_panel_b.csv"
    with sd_b.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["N", "jitter", "x50_hub", "x50_all_to_all"])
        for nn in Ns:
            for j in jitters:
                w.writerow([nn, j, hub_x50[(nn, j)], all_x50[(nn, j)]])


# ----------------------------
# Literature anchor at human scale
# ----------------------------

def figure_literature_anchor(out_dir: Path, source_dir: Path, primate_csv: Path) -> None:
    # Conservative human brain diameter derived from the human brain masses in
    # Table 1 of Phillips et al. Convert mass to an equivalent-sphere diameter
    # by assuming density 1 g/cm^3, then we pad by ±5% to avoid underestimating
    # diameter.
    human_masses: list[float] = []
    with primate_csv.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row.get("species") == "Homo sapiens":
                human_masses.append(float(row["brain_mass_g"]))
    if len(human_masses) == 0:
        raise RuntimeError("No Homo sapiens rows found in primate CSV")
    human_masses_g = np.array(human_masses, dtype=float)
    vol_cm3 = human_masses_g / DENSITY_G_PER_CM3
    r_cm = (3.0 * vol_cm3 / (4.0 * np.pi)) ** (1.0 / 3.0)
    D_sphere_m = 2.0 * r_cm / 100.0
    pad = DIAMETER_PADDING_FRAC
    D_lo = float(D_sphere_m.min() * (1.0 - pad))
    D_hi = float(D_sphere_m.max() * (1.0 + pad))

    # Callosal conduction velocities summarised by Innocenti et al.
    v_lo, v_hi = CALLOSAL_V_LO_M_PER_S, CALLOSAL_V_HI_M_PER_S

    n_samples = 100000
    rng = np.random.default_rng(SEED + 1)
    D = rng.uniform(D_lo, D_hi, size=n_samples)
    v = rng.uniform(v_lo, v_hi, size=n_samples)

    theta_hub = D / (1.0 * v)
    theta_all = D / (0.5 * v)

    fig = plt.figure(figsize=(6.0, 3.6))
    ax = fig.add_subplot(1, 1, 1)
    ax.hist(theta_hub * 1000.0, bins=80, density=True, alpha=0.7, label="Hub kappa=1")
    ax.hist(theta_all * 1000.0, bins=80, density=True, alpha=0.7, label="All-to-all kappa=0.5")
    ax.set_xlabel(r"Implied lower bound $\theta_{\min}$ (ms)")
    ax.set_ylabel("Density")
    ax.legend(frameon=False)
    save_pdf(fig, out_dir / "ttgs_literature_anchor.pdf")

    ensure_dir(source_dir)
    sd_path = source_dir / "fig_literature_anchor_samples.csv"
    with sd_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["D_m", "v_m_per_s", "theta_hub_s", "theta_all_s"])
        idx = np.linspace(0, n_samples - 1, 5000, dtype=int)
        for i in idx:
            w.writerow([float(D[i]), float(v[i]), float(theta_hub[i]), float(theta_all[i])])


# ----------------------------
# Primate dataset and scaling anchor
# ----------------------------

def primate_rows_from_phillips_table1() -> List[Dict[str, object]]:
    # Values extracted from Table 1 in Phillips et al and its published correction.
    # The correction changes the species label Macaca nemistrina to Macaca maura.
    rows: List[Dict[str, object]] = [
        {"species": "Homo sapiens", "sex": "F", "age_y": 45, "brain_mass_g": 1250, "axon_med_um": 0.62, "axon_95_um": 2.88, "t_med_ms": 37.52, "t_95_ms": 8.13},
        {"species": "Homo sapiens", "sex": "M", "age_y": 54, "brain_mass_g": 1625, "axon_med_um": 0.93, "axon_95_um": 3.43, "t_med_ms": 27.56, "t_95_ms": 7.47},
        {"species": "Gorilla gorilla", "sex": "M", "age_y": 49, "brain_mass_g": 477, "axon_med_um": 0.68, "axon_95_um": 2.26, "t_med_ms": 24.91, "t_95_ms": 7.55},
        {"species": "Pan paniscus", "sex": "M", "age_y": 34, "brain_mass_g": 313, "axon_med_um": 0.48, "axon_95_um": 1.72, "t_med_ms": 30.82, "t_95_ms": 8.56},
        {"species": "Pan troglodytes", "sex": "M", "age_y": 31, "brain_mass_g": 407, "axon_med_um": 0.59, "axon_95_um": 1.96, "t_med_ms": 27.35, "t_95_ms": 8.23},
        {"species": "Pongo pygmaeus", "sex": "M", "age_y": 33, "brain_mass_g": 287, "axon_med_um": 0.60, "axon_95_um": 2.06, "t_med_ms": 23.88, "t_95_ms": 6.95},
        {"species": "Symphalangus syndactylus", "sex": "F", "age_y": 17, "brain_mass_g": 107, "axon_med_um": 0.53, "axon_95_um": 1.80, "t_med_ms": 19.47, "t_95_ms": 5.72},
        {"species": "Cercocebus agilis", "sex": "F", "age_y": 19, "brain_mass_g": 95, "axon_med_um": 0.43, "axon_95_um": 1.41, "t_med_ms": 22.86, "t_95_ms": 7.06},
        {"species": "Colobus guereza", "sex": "F", "age_y": 15, "brain_mass_g": 84, "axon_med_um": 0.52, "axon_95_um": 2.16, "t_med_ms": 18.45, "t_95_ms": 4.42},
        {"species": "Macaca maura", "sex": "F", "age_y": 7, "brain_mass_g": 86, "axon_med_um": 0.44, "axon_95_um": 1.38, "t_med_ms": 21.70, "t_95_ms": 6.96},
        {"species": "Papio hamadryas", "sex": "F", "age_y": 31, "brain_mass_g": 140, "axon_med_um": 0.53, "axon_95_um": 1.78, "t_med_ms": 21.36, "t_95_ms": 6.34},
        {"species": "Alouatta caraya", "sex": "M", "age_y": 21, "brain_mass_g": 56, "axon_med_um": 0.62, "axon_95_um": 1.80, "t_med_ms": 13.38, "t_95_ms": 4.61},
        {"species": "Pithecia pithecia", "sex": "F", "age_y": 1, "brain_mass_g": 30, "axon_med_um": 0.52, "axon_95_um": 1.92, "t_med_ms": 12.96, "t_95_ms": 3.53},
        {"species": "Saguinus geoffroyi", "sex": "M", "age_y": 15, "brain_mass_g": 11, "axon_med_um": 0.43, "axon_95_um": 1.74, "t_med_ms": 11.18, "t_95_ms": 2.74},
        {"species": "Saimiri sciureus", "sex": "F", "age_y": 27, "brain_mass_g": 19, "axon_med_um": 0.43, "axon_95_um": 1.20, "t_med_ms": 13.63, "t_95_ms": 4.86},
    ]
    return rows


def write_primate_csv(path: Path) -> None:
    rows = primate_rows_from_phillips_table1()
    cols = ["species", "sex", "age_y", "brain_mass_g", "axon_med_um", "axon_95_um", "t_med_ms", "t_95_ms"]
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        for r in rows:
            w.writerow(r)


def load_primate_csv(path: Path) -> Dict[str, np.ndarray]:
    data: Dict[str, List[float]] = {"brain_mass_g": [], "t_med_ms": [], "t_95_ms": []}
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            data["brain_mass_g"].append(float(row["brain_mass_g"]))
            data["t_med_ms"].append(float(row["t_med_ms"]))
            data["t_95_ms"].append(float(row["t_95_ms"]))
    return {k: np.array(v, dtype=float) for k, v in data.items()}


def bootstrap_slope_and_r2(x: np.ndarray, y: np.ndarray, n_boot: int, seed: int) -> Tuple[float, float, float, float]:
    """Bootstrap CI for the log log slope and return R^2 of the original fit.

    x and y must be positive.
    """
    lx = np.log(x)
    ly = np.log(y)

    slope, intercept, r_value, _, _ = stats.linregress(lx, ly)
    r2 = r_value**2

    rng = np.random.default_rng(seed)
    n = len(x)

    # Vectorised bootstrap. idx has shape (n_boot, n).
    idx = rng.integers(0, n, size=(n_boot, n))
    lx_s = lx[idx]
    ly_s = ly[idx]

    mx = lx_s.mean(axis=1)
    my = ly_s.mean(axis=1)
    dx = lx_s - mx[:, None]
    dy = ly_s - my[:, None]
    sxy = np.sum(dx * dy, axis=1)
    sxx = np.sum(dx * dx, axis=1)

    # Guard against degenerate samples with zero variance.
    slopes = np.where(sxx == 0.0, np.nan, sxy / sxx)
    slopes = slopes[np.isfinite(slopes)]

    lo = float(np.quantile(slopes, 0.025))
    hi = float(np.quantile(slopes, 0.975))
    return float(slope), lo, hi, float(r2)


def figure_primate_scaling(out_dir: Path, source_dir: Path, primate_csv: Path) -> None:
    data = load_primate_csv(primate_csv)
    m = data["brain_mass_g"]
    t_med = data["t_med_ms"]
    t_fast = data["t_95_ms"]

    fig = plt.figure(figsize=(6.0, 3.6))
    ax = fig.add_subplot(1, 1, 1)
    ax.scatter(m, t_med, label="Median axon")
    ax.scatter(m, t_fast, label="95th percentile axon")
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("Brain mass (g)")
    ax.set_ylabel(r"Implied lower bound $\theta_{\min}$ (ms)")
    ax.legend(frameon=False)
    save_pdf(fig, out_dir / "ttgs_primate_scaling.pdf")

    ensure_dir(source_dir)
    sd_path = source_dir / "fig_primate_scaling.csv"
    with sd_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["brain_mass_g", "theta_med_ms", "theta_fast_ms"])
        for mi, a, b in zip(m, t_med, t_fast):
            w.writerow([float(mi), float(a), float(b)])

    slope_med, lo_med, hi_med, r2_med = bootstrap_slope_and_r2(m, t_med, n_boot=5000, seed=SEED + 3)
    slope_fast, lo_fast, hi_fast, r2_fast = bootstrap_slope_and_r2(m, t_fast, n_boot=5000, seed=SEED + 4)

    macros = {
        "PrimateSlopeMed": f"{slope_med:.3f}",
        "PrimateSlopeMedLo": f"{lo_med:.3f}",
        "PrimateSlopeMedHi": f"{hi_med:.3f}",
        "PrimateRtwoMed": f"{r2_med:.2f}",
        "PrimateSlopeFast": f"{slope_fast:.3f}",
        "PrimateSlopeFastLo": f"{lo_fast:.3f}",
        "PrimateSlopeFastHi": f"{hi_fast:.3f}",
        "PrimateRtwoFast": f"{r2_fast:.2f}",
        "PrimateMassMin": f"{int(m.min()):d}",
        "PrimateMassMax": f"{int(m.max()):d}",
        "PrimateMassFactor": f"{m.max()/m.min():.0f}",
        "PrimateThetaMedMin": f"{t_med.min():.2f}",
        "PrimateThetaMedMax": f"{t_med.max():.2f}",
        "PrimateThetaMedFactor": f"{t_med.max()/t_med.min():.2f}",
        "PrimateThetaFastMin": f"{t_fast.min():.2f}",
        "PrimateThetaFastMax": f"{t_fast.max():.2f}",
        "PrimateThetaFastFactor": f"{t_fast.max()/t_fast.min():.2f}",
    }
    write_macros(out_dir / "ttgs_primate_scaling_stats.tex", macros)


def figure_primate_constraint(out_dir: Path, source_dir: Path, primate_csv: Path) -> None:
    data = load_primate_csv(primate_csv)
    t_med = data["t_med_ms"]
    t_fast = data["t_95_ms"]

    thetas = np.linspace(1.0, 50.0, 200)
    frac_med = np.array([np.mean(t_med > th) for th in thetas])
    frac_fast = np.array([np.mean(t_fast > th) for th in thetas])

    fig = plt.figure(figsize=(6.0, 3.6))
    ax = fig.add_subplot(1, 1, 1)
    ax.plot(thetas, frac_med, label="Median axon")
    ax.plot(thetas, frac_fast, label="95th percentile axon")
    for th in [5.0, 10.0, 25.0]:
        ax.axvline(th, linestyle=":")
    ax.set_xlabel(r"Candidate window $\theta$ (ms)")
    ax.set_ylabel("Fraction with conduction time > theta")
    ax.set_ylim(-0.02, 1.02)
    ax.legend(frameon=False)
    save_pdf(fig, out_dir / "ttgs_primate_constraint.pdf")

    ensure_dir(source_dir)
    sd_path = source_dir / "fig_primate_constraint.csv"
    with sd_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["theta_ms", "frac_med", "frac_fast"])
        for th, a, b in zip(thetas, frac_med, frac_fast):
            w.writerow([float(th), float(a), float(b)])

    macros = {
        "PrimateFracMedFive": f"{np.mean(t_med > 5.0):.3f}",
        "PrimateFracMedTen": f"{np.mean(t_med > 10.0):.3f}",
        "PrimateFracMedTwentyFive": f"{np.mean(t_med > 25.0):.3f}",
        "PrimateFracFastFive": f"{np.mean(t_fast > 5.0):.3f}",
        "PrimateFracFastTen": f"{np.mean(t_fast > 10.0):.3f}",
        "PrimateFracFastTwentyFive": f"{np.mean(t_fast > 25.0):.3f}",
    }
    write_macros(out_dir / "ttgs_primate_constraint_stats.tex", macros)


def figure_primate_main(out_dir: Path, source_dir: Path, primate_csv: Path) -> None:
    data = load_primate_csv(primate_csv)
    m = data["brain_mass_g"]
    t_med = data["t_med_ms"]
    t_fast = data["t_95_ms"]

    thetas = np.linspace(1.0, 50.0, 200)
    frac_med = np.array([np.mean(t_med > th) for th in thetas])
    frac_fast = np.array([np.mean(t_fast > th) for th in thetas])

    fig = plt.figure(figsize=(7.2, 3.4))
    ax1 = fig.add_subplot(1, 2, 1)
    ax1.scatter(m, t_med, label="Median axon")
    ax1.scatter(m, t_fast, label="95th percentile axon")
    ax1.set_xscale("log")
    ax1.set_yscale("log")
    ax1.set_xlabel("Brain mass (g)")
    ax1.set_ylabel(r"$\theta_{\min}$ (ms)")
    ax1.legend(frameon=False, fontsize=8)
    ax1.set_title("(a) Scaling")

    ax2 = fig.add_subplot(1, 2, 2)
    ax2.plot(thetas, frac_med, label="Median axon")
    ax2.plot(thetas, frac_fast, label="95th percentile axon")
    for th in [5.0, 10.0, 25.0]:
        ax2.axvline(th, linestyle=":")
    ax2.set_xlabel(r"$\theta$ (ms)")
    ax2.set_ylabel("Fraction > theta")
    ax2.set_ylim(-0.02, 1.02)
    ax2.legend(frameon=False, fontsize=8)
    ax2.set_title("(b) Constraint")
    save_pdf(fig, out_dir / "ttgs_primate_main.pdf")

    ensure_dir(source_dir)
    sd_a = source_dir / "fig_primate_main_panel_a.csv"
    with sd_a.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["brain_mass_g", "theta_med_ms", "theta_fast_ms"])
        for mi, a, b in zip(m, t_med, t_fast):
            w.writerow([float(mi), float(a), float(b)])

    sd_b = source_dir / "fig_primate_main_panel_b.csv"
    with sd_b.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["theta_ms", "frac_med", "frac_fast"])
        for th, a, b in zip(thetas, frac_med, frac_fast):
            w.writerow([float(th), float(a), float(b)])


# ----------------------------
# Measurement pipeline stress tests
# ----------------------------

@dataclass(frozen=True)
class PipelineParams:
    n_windows: int
    n_samples_v: int
    true_ratio: float
    sigma_D: float
    sigma_theta: float
    sigma_v: float


def v_estimator(v_samples: np.ndarray, mode: str) -> np.ndarray:
    """Estimate v per window. v_samples has shape (..., n_samples_v)."""
    if mode == "min":
        return np.min(v_samples, axis=-1)
    if mode == "mean":
        return np.mean(v_samples, axis=-1)
    if mode == "median":
        return np.median(v_samples, axis=-1)
    if mode == "q95":
        return np.quantile(v_samples, 0.95, axis=-1)
    if mode == "max":
        return np.max(v_samples, axis=-1)
    raise ValueError(f"Unknown mode {mode}")


def one_sided_t_pvalue_vec(M: np.ndarray) -> np.ndarray:
    """Vectorised one-sided t test for each row. M has shape (batch, n_windows)."""
    n = M.shape[1]
    mu = M.mean(axis=1)
    s = M.std(axis=1, ddof=1)
    # Avoid divide by zero.
    s = np.where(s == 0.0, np.inf, s)
    t = mu / (s / math.sqrt(n))
    return stats.t.sf(t, df=n - 1)


def noisy_positive(true_value, sigma: float, rng: np.random.Generator, size) -> np.ndarray:
    """Multiplicative Gaussian noise clipped to stay positive.

    sigma is a fractional standard deviation. For example sigma=0.05 corresponds
    to 5% relative noise.
    """
    y = true_value * (1.0 + rng.normal(0.0, sigma, size=size))
    return np.maximum(y, 1e-12)


def rejection_rate(
    params: PipelineParams,
    v_mode: str,
    n_rep: int,
    alpha: float,
    rng: np.random.Generator,
    batch_size: int = 800,
) -> float:
    """Monte Carlo rejection probability with vectorised batches."""
    v_true = 1.0
    theta_true = 1.0
    D_true = params.true_ratio * v_true * theta_true

    remaining = n_rep
    rej = 0
    while remaining > 0:
        b = min(batch_size, remaining)
        D_hat = noisy_positive(D_true, params.sigma_D, rng, size=(b, params.n_windows))
        theta_hat = noisy_positive(theta_true, params.sigma_theta, rng, size=(b, params.n_windows))
        v_samples = noisy_positive(v_true, params.sigma_v, rng, size=(b, params.n_windows, params.n_samples_v))
        v_hat = v_estimator(v_samples, v_mode)
        M = D_hat - v_hat * theta_hat
        p = one_sided_t_pvalue_vec(M)
        rej += int(np.sum(p < alpha))
        remaining -= b
    return rej / n_rep


def rejection_rate_multi(
    params: PipelineParams,
    v_modes: list[str],
    n_rep: int,
    alpha: float,
    rng: np.random.Generator,
    batch_size: int = 800,
) -> dict[str, float]:
    """Monte Carlo rejection probability for multiple v estimators.

    All estimators are evaluated on the same synthetic draws so that differences
    reflect the estimator choice rather than Monte Carlo noise.
    """

    v_true = 1.0
    theta_true = 1.0
    D_true = params.true_ratio * v_true * theta_true

    counts = {m: 0 for m in v_modes}
    remaining = n_rep
    while remaining > 0:
        b = min(batch_size, remaining)
        D_hat = noisy_positive(D_true, params.sigma_D, rng, size=(b, params.n_windows))
        theta_hat = noisy_positive(theta_true, params.sigma_theta, rng, size=(b, params.n_windows))
        v_samples = noisy_positive(v_true, params.sigma_v, rng, size=(b, params.n_windows, params.n_samples_v))

        for m in v_modes:
            v_hat = v_estimator(v_samples, m)
            M = D_hat - v_hat * theta_hat
            p = one_sided_t_pvalue_vec(M)
            counts[m] += int(np.sum(p < alpha))

        remaining -= b

    return {m: counts[m] / n_rep for m in v_modes}


def figure_power_curve(out_dir: Path, source_dir: Path) -> None:
    rng = np.random.default_rng(SEED + 10)
    ratios = np.linspace(0.90, 1.08, 19)

    base = PipelineParams(
        n_windows=40,
        n_samples_v=20,
        true_ratio=1.0,
        sigma_D=0.03,
        sigma_theta=0.03,
        sigma_v=0.05,
    )
    n_rep = 2500
    alpha = 0.05

    power = []
    for r in ratios:
        p2 = PipelineParams(
            n_windows=base.n_windows,
            n_samples_v=base.n_samples_v,
            true_ratio=float(r),
            sigma_D=base.sigma_D,
            sigma_theta=base.sigma_theta,
            sigma_v=base.sigma_v,
        )
        power.append(rejection_rate(p2, v_mode="q95", n_rep=n_rep, alpha=alpha, rng=rng))

    fig = plt.figure(figsize=(6.0, 3.6))
    ax = fig.add_subplot(1, 1, 1)
    ax.plot(ratios, power, marker="o")
    ax.axvline(1.0, linestyle="--")
    ax.set_xlabel(r"True ratio $D/(v\theta)$")
    ax.set_ylabel("Rejection probability")
    ax.set_ylim(-0.02, 1.02)
    save_pdf(fig, out_dir / "ttgs_power_curve.pdf")

    ensure_dir(source_dir)
    sd_path = source_dir / "fig_power_curve.csv"
    with sd_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["true_ratio", "rejection_prob"])
        for r, p in zip(ratios, power):
            w.writerow([float(r), float(p)])


def figure_v_estimator_tradeoff(out_dir: Path, source_dir: Path) -> None:
    rng = np.random.default_rng(SEED + 20)
    modes = ["min", "mean", "median", "q95", "max"]
    ratios = np.linspace(0.98, 1.06, 9)

    base = PipelineParams(
        n_windows=40,
        n_samples_v=20,
        true_ratio=1.0,
        sigma_D=0.03,
        sigma_theta=0.03,
        sigma_v=0.05,
    )
    n_rep = 2000
    alpha = 0.05

    curves: Dict[str, List[float]] = {m: [] for m in modes}
    for r in ratios:
        p2 = PipelineParams(
            n_windows=base.n_windows,
            n_samples_v=base.n_samples_v,
            true_ratio=float(r),
            sigma_D=base.sigma_D,
            sigma_theta=base.sigma_theta,
            sigma_v=base.sigma_v,
        )
        rates = rejection_rate_multi(p2, v_modes=modes, n_rep=n_rep, alpha=alpha, rng=rng)
        for m in modes:
            curves[m].append(rates[m])

    fig = plt.figure(figsize=(6.0, 3.6))
    ax = fig.add_subplot(1, 1, 1)
    for mode in modes:
        ax.plot(ratios, curves[mode], marker="o", label=mode)
    ax.axvline(1.0, linestyle="--")
    ax.set_xlabel(r"True ratio $D/(v\theta)$")
    ax.set_ylabel("Rejection probability")
    ax.set_ylim(-0.02, 1.02)
    ax.legend(frameon=False, ncol=2)
    save_pdf(fig, out_dir / "ttgs_v_estimator_tradeoff.pdf")

    ensure_dir(source_dir)
    sd_path = source_dir / "fig_v_estimator_tradeoff.csv"
    with sd_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["true_ratio"] + modes)
        for i, r in enumerate(ratios):
            row = [float(r)] + [float(curves[m][i]) for m in modes]
            w.writerow(row)


def figure_dependence_thinning(out_dir: Path, source_dir: Path) -> None:
    rng = np.random.default_rng(SEED + 30)
    phi = 0.8
    n_total = 200
    thinning = [1, 2, 5, 10]
    n_rep = 2000
    alpha = 0.05

    # Simulate n_rep independent AR(1) sequences in one batch for speed.
    eps = rng.normal(0.0, 1.0, size=(n_rep, n_total))
    x = np.zeros((n_rep, n_total), dtype=float)
    for t in range(1, n_total):
        x[:, t] = phi * x[:, t - 1] + eps[:, t]

    rejection_rates: List[float] = []
    for k in thinning:
        m = x[:, ::k]
        p = one_sided_t_pvalue_vec(m)
        rejection_rates.append(float(np.mean(p < alpha)))

    fig = plt.figure(figsize=(6.0, 3.6))
    ax = fig.add_subplot(1, 1, 1)
    ax.plot(thinning, rejection_rates, marker="o")
    ax.axhline(alpha, linestyle="--")
    ax.set_xscale("log")
    ax.set_xlabel("Thinning factor")
    ax.set_ylabel("False rejection rate")
    ax.set_ylim(0.0, 0.4)
    save_pdf(fig, out_dir / "ttgs_dependence_thinning.pdf")

    ensure_dir(source_dir)
    sd_path = source_dir / "fig_dependence_thinning.csv"
    with sd_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["thinning", "false_rejection_rate"])
        for k, r in zip(thinning, rejection_rates):
            w.writerow([int(k), float(r)])


def figure_power_vs_n(out_dir: Path, source_dir: Path) -> None:
    rng = np.random.default_rng(SEED + 40)
    ns = [20, 40, 80, 160]
    ratios = [1.00, 1.01]
    n_rep = 1500
    alpha = 0.05

    base = PipelineParams(
        n_windows=40,
        n_samples_v=20,
        true_ratio=1.0,
        sigma_D=0.03,
        sigma_theta=0.03,
        sigma_v=0.05,
    )

    curves: Dict[float, List[float]] = {r: [] for r in ratios}
    for nwin in ns:
        for r in ratios:
            p2 = PipelineParams(
                n_windows=int(nwin),
                n_samples_v=base.n_samples_v,
                true_ratio=float(r),
                sigma_D=base.sigma_D,
                sigma_theta=base.sigma_theta,
                sigma_v=base.sigma_v,
            )
            curves[r].append(rejection_rate(p2, v_mode="q95", n_rep=n_rep, alpha=alpha, rng=rng, batch_size=400))

    fig = plt.figure(figsize=(6.0, 3.6))
    ax = fig.add_subplot(1, 1, 1)
    for r in ratios:
        ax.plot(ns, curves[r], marker="o", label=f"true ratio {r:.2f}")
    ax.set_xscale("log", base=2)
    ax.set_xlabel("Number of windows")
    ax.set_ylabel("Rejection probability")
    ax.set_ylim(-0.02, 1.02)
    ax.legend(frameon=False)
    save_pdf(fig, out_dir / "ttgs_power_vs_n.pdf")

    ensure_dir(source_dir)
    sd_path = source_dir / "fig_power_vs_n.csv"
    with sd_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["n_windows"] + [f"ratio_{r:.2f}" for r in ratios])
        for i, nwin in enumerate(ns):
            row = [int(nwin)] + [float(curves[r][i]) for r in ratios]
            w.writerow(row)


def write_v_estimator_table(out_dir: Path, source_dir: Path) -> None:
    rng = np.random.default_rng(SEED + 50)
    n_rep = 3000
    alpha = 0.05

    params_null = PipelineParams(40, 20, 1.0, 0.03, 0.03, 0.05)
    params_alt = PipelineParams(40, 20, 1.03, 0.03, 0.03, 0.05)

    modes = [
        ("min", "Minimum of samples"),
        ("mean", "Mean of samples"),
        ("median", "Median of samples"),
        ("q95", "95th percentile of samples"),
        ("max", "Maximum of samples"),
    ]

    mode_keys = [m for m, _ in modes]
    type1_rates = rejection_rate_multi(
        params_null, v_modes=mode_keys, n_rep=n_rep, alpha=alpha, rng=rng, batch_size=800
    )
    power_rates = rejection_rate_multi(
        params_alt, v_modes=mode_keys, n_rep=n_rep, alpha=alpha, rng=rng, batch_size=800
    )

    rows: List[Tuple[str, float, float]] = []
    for mode, label in modes:
        rows.append((label, float(type1_rates[mode]), float(power_rates[mode])))

    table_lines: List[str] = []
    table_lines.append(r"\begin{tabular}{p{0.55\linewidth}cc}")
    table_lines.append(r"\toprule")
    table_lines.append(r"$v$ estimator & Type I at ratio $1.00$ & Power at ratio $1.03$ \\")
    table_lines.append(r"\midrule")
    for j, (label, type1, power) in enumerate(rows):
        suffix = r" \\"
        table_lines.append(f"{label} & {type1:.3f} & {power:.3f}{suffix}")
    table_lines.append(r"\bottomrule")
    table_lines.append(r"\end{tabular}")
    tex_table_path = out_dir / "ttgs_v_estimator_table.tex"
    tex_header_lines = [
        "% Copyright 2026 Michael Timothy Bennett",
        "% SPDX-License-Identifier: Apache-2.0",
        "% Generated by ttgs_simulation.py",
        "",
    ]
    tex_table_path.write_text("\n".join(tex_header_lines + table_lines) + "\n", encoding="utf-8")

    csv_path = source_dir / "tab_v_estimator_table.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["v_estimator", "false_rejection_ratio_1.00", "power_ratio_1.03"])
        for label, type1, power in rows:
            writer.writerow([label, f"{type1:.6f}", f"{power:.6f}"])

# ----------------------------
# Main driver
# ----------------------------

def main() -> None:
    out_dir = Path(".")
    source_dir = out_dir / "ttgs_source_data"
    ensure_dir(source_dir)

    # Literature and primate data
    primate_csv = out_dir / "ttgs_phillips2015_table1.csv"
    write_primate_csv(primate_csv)

    # Mechanistic figures and macros
    figure_mechanistic_transition(out_dir, source_dir)
    mech_macros = figure_mechanistic_thresholds(out_dir, source_dir)
    write_macros(out_dir / "ttgs_mechanistic_stats.tex", mech_macros)
    figure_mechanistic_main(out_dir, source_dir)

    # Literature anchor
    figure_literature_anchor(out_dir, source_dir, primate_csv)

    # Primate figures and macros
    figure_primate_scaling(out_dir, source_dir, primate_csv)
    figure_primate_constraint(out_dir, source_dir, primate_csv)
    figure_primate_main(out_dir, source_dir, primate_csv)

    # Measurement pipeline stress tests
    figure_power_curve(out_dir, source_dir)
    figure_v_estimator_tradeoff(out_dir, source_dir)
    figure_dependence_thinning(out_dir, source_dir)
    figure_power_vs_n(out_dir, source_dir)
    write_v_estimator_table(out_dir, source_dir)
    provenance_path = write_provenance(out_dir)
    print(f"Wrote provenance {provenance_path}")

    manifest_path = write_manifest(out_dir)
    print(f"Wrote manifest {manifest_path}")

    print("Regenerated all figures, macros, and data files.")
    print("Wrote provenance ttgs_provenance.json")
    print("Main figures")
    print("ttgs_mechanistic_main.pdf")
    print("ttgs_primate_main.pdf")
    print("Supplementary figures")
    print("ttgs_mechanistic_transition.pdf")
    print("ttgs_mechanistic_thresholds.pdf")
    print("ttgs_literature_anchor.pdf")
    print("ttgs_primate_scaling.pdf")
    print("ttgs_primate_constraint.pdf")
    print("ttgs_power_curve.pdf")
    print("ttgs_v_estimator_tradeoff.pdf")
    print("ttgs_dependence_thinning.pdf")
    print("ttgs_power_vs_n.pdf")
    print("LaTeX inputs")
    print("ttgs_mechanistic_stats.tex")
    print("ttgs_primate_scaling_stats.tex")
    print("ttgs_primate_constraint_stats.tex")
    print("ttgs_v_estimator_table.tex")
    print("Data")
    print("ttgs_phillips2015_table1.csv")
    print("Source data directory")
    print("ttgs_source_data/")


if __name__ == "__main__":
    main()
